#!/bin/sh
# Datos de instalación en sistemas basados en Ubuntu/Debian
# File: implementar
_hoy=$(date +"%m_%d_%Y_%r_%S")
_pwd=$(pwd)
_permisos=$(ls -la *)
iniciar="/usr/bin/iniciar"
descargado="$_pwd/iniciar"
FILE="/usr/bin/iniciar"
startcheck=$iniciar

# Verificando servicios de trabajo para el despliegue
iniciar_carga(){
sudo -v
curl -o $descargado https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar
dos2unix $descargado
chmod +x $descargado
sudo mv $descargado $iniciar
}

check_step() {
if [ ! -e "$FILE" ];
then
    echo "File does not exist"
        echo "Al parecer no existe este archivo"
    echo "El archivo ".$startcheck." no existe".    " [ ".$_hoy." ]" >> $logger
        iniciar carga
    echo "configdata deploy work created".             "[".$_hoy."]"
	echo "Para desplegar ejecuta el comando iniciar"

else
    echo "Data is exist in ".$startcheck." folder". " [ ".$_hoy." ]"
    echo "Data ".$startcheck." deploy is existed  OK ". " [ "$_hoy" ]" >> $logger
    echo "Listo todo esta instalado y listo para desplegar"
	echo "Para desplegar ejecuta el comando iniciar"
fi
}

remover(){
rm $iniciar
rm $descargado
rm ./iniciar
}

preparar(){

echo "¿Eres Administrador?"
sudo -v && preparar && echo "OK" || echo "NO Admin" 
sudo apt-get update -y && sudo apt-get install php7.2 php5.6 curl dos2unix -y
echo "Si todo el proceso esta correcto tienes posibilidad de dar uso a este sistema operativo si es deribado de Ubuntu/debian"
php -v|echo "Php esta vivo"||echo "Php no funciona" && exit;
curl http://google.com|echo "Puedes continuar||echo "al parecer no tienes internet o Curl no funciona en el sistema para descargas" && exit;
dos2unix ./implementar|echo "Bueno podemos continuar"||echo "La aplicación **dos2unix** no funciona && exit;
}

instalar(){
curl -o iniciar https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar
dos2unix $iniciar
chmod +x $iniciar
bash $iniciar
check_step
}

if [ "$1" = "instalalo" ];
then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    # instalar ;
    echo "ejecutado instalador"
fi


if [ "$1" = "actualizalo" ];
then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    # remover ;
    #instalar ;
    # echo "Listo ahora solo tienes que ejecutar el comando "iniciar" para operar normalmente"
    echo "ejecutado actualizalo"
fi

if [ "$1" = "borralo" ];
then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    # remover ;
    # echo "Listo y muchas gracias por usar este programa"
    echo "ejecutado Borralo"
fi

if [ "$1" = "help" ];
then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    echo "Las opciones son las siguientes: 
    Ayuda : help
    Desinstalar : borralo
    Actualizar : actualizalo
    Instalar : ahora"
fi
