#!/bin/sh
# Datos de instalación en sistemas basados en Ubuntu/Debian
# File: implementar
_hoy=$(date +"%m_%d_%Y_%r_%S")
_pwd=$(pwd)
_permisos=$(ls -la *)
iniciar="/usr/bin/iniciar"
descargado="$_pwd/iniciar"
FILE="/usr/bin/iniciar"
startcheck=$iniciar

# Verificando servicios de trabajo para el despliegue
iniciar_carga(){
$(sudo -v)
$(curl -o $iniciar https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar)
$(dos2unix $iniciar)
$(chmod +x $iniciar)
$(sudo cp iniciar $iniciar)
}

check_step() {
if [ ! -e "$startcheck" ];
then
    echo "File does not exist"
        echo "Al parecer no existe este archivo"
    echo "El archivo ".$startcheck." no existe".    " [ ".$_hoy." ]" >> $logger
        iniciar carga
    echo "configdata deploy work created".             "[".$_hoy."]"
	echo "Para desplegar ejecuta el comando iniciar"

else
    echo "Data is exist in ".$startcheck." folder". " [ ".$_hoy." ]"
    echo "Data ".$startcheck." deploy is existed  OK ". " [ "$_hoy" ]" >> $logger
    echo "Listo todo esta instalado y listo para desplegar"
	echo "Para desplegar ejecuta el comando iniciar"
fi
}

remover(){
rm $iniciar
rm $descargado
rm ./iniciar
}

instalar(){
echo "¿Eres Administrador?"
$(sudo -v && echo "OK" || echo "NOK" sudo apt update -y && sudo apt install php7.2 php5.6 curl dos2unix -y)

curl -o iniciar https://raw.githubusercontent.com/juanma386/desplegar/master/iniciar
dos2unix $iniciar
chmod +x $iniciar
bash $iniciar
check_step
}

if [ $1 ="instalalo" ]; then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    instalar ;
fi


if [ $1 ="actualizalo" ]; then
     echo 'ahora ejecuta la instalación con "./implementar ahora"';
else
    remover ;
    instalar ;
    echo "Listo ahora solo tienes que ejecutar el comando "iniciar" para operar normalmente"
fi


